### ISSUE TITLE
Mind of switching license to MIT or BSD?

### ISSUE THREAD

**Issue by therealmarv** [William-Yeh/ansible-nodejs#1]
MIT (or BSD) are easier to understand and are nearly the same as Apache License 2.0. Sure they are not as precise as the 1400 words Apache license and for a big SW project or company (like e.g. Android and Google) I understand to go for the more precise Apache License 2.0 but I think for an Ansible role it would be beneficial to go with a more simple license.
Actually I wanted to use your role for one project but then I decided against it because Apache License 2.0 seemed overkill for such a part (but this is only my opinion).

**Comment by William-Yeh** [comment]
Good idea!  I've changed it since https://github.com/William-Yeh/ansible-nodejs/commit/cc47631dfedd229e91ae264af6d3702279db6c26 .
