### ISSUE TITLE
Version checks are failing with latest update

### ISSUE THREAD

**Issue by rjmackay** [William-Yeh/ansible-nodejs#5]
This commit https://github.com/William-Yeh/ansible-nodejs/commit/306f0efce7ef2198e282d591fdce0f2dbfcd3a5f switched to using `nodejs_version | match('^5.*$')` for version checks. However this breaks when nodejs_version is a number not a string (ie. `nodejs_version: 0.12`)

```
{"failed": true, "msg": "ERROR! The conditional check 'nodejs_version | match('^5.*$')' failed. The error was: ERROR! an unexpected type error occurred. Error was expected string or buffer\n\nThe error appears to have been in '/private/etc/ansible/roles/williamyeh.nodejs/tasks/use-apt.yml': line 29, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: add NodeSource repository for Node.js 5.0\n      ^ here\n"}
```

**Comment by William-Yeh** [comment]
Thanks for reporting this issue.

Both _numeric_ and _string_ forms are now acceptable for the nodejs_version variable. 
See https://github.com/William-Yeh/ansible-nodejs/commit/c542f7e386c1c72a09ace1fa9fb93386781f646d

**Comment by rjmackay** [comment]
Amazing. Thank you!
