### ISSUE TITLE
NVM command not availbale ?

### ISSUE THREAD

**Issue by anthony-robin** [William-Yeh/ansible-nodejs#6]
After installing your recipes on my server I was able to use the `node` and `npm` commands properly but not `nvm` (No command 'nvm' found). 
I'm not sure if it is a bug or a wanted behavior.

I tried it on a Vagrant local machine with Ubuntu 14.04 logged in as `vagrant` user by ssh.

**Comment by William-Yeh** [comment]
As mentioned in the README: "Older versions (before 2015-05-08) are based on NVM".

Currently, the role doesn't try to install nvm.

**Comment by anthony-robin** [comment]
That's what I thought but I wasn't sure I understood properly.
Thanks !
